### ISSUE TITLE
Could not load 'guard/shell'

### ISSUE THREAD

**Issue by georgeu2000** [hawx/guard-shell#27]
Does guard-shell work with Ruby 2.4.1 and 2.14.1?

Using Guard Shell 0.7.1

Guardfile:
```
guard :shell do
  
end
```

Error:
```
Could not load 'guard/shell' or find class Guard::Shell
16:04:39 - ERROR - Error is: cannot load such file -- guard/shell
16:04:39 - ERROR - /Users/george/.rbenv/versions/2.4.1/gemsets/crystal-news/gems/guard-2.14.1/lib/guard/plugin_util.rb:105:in `require'
> [#] /Users/george/.rbenv/versions/2.4.1/gemsets/crystal-news/gems/guard-2.14.1/lib/guard/plugin_util.rb:105:in `rescue in plugin_class'
> [#] /Users/george/.rbenv/versions/2.4.1/gemsets/crystal-news/gems/guard-2.14.1/lib/guard/plugin_util.rb:97:in `plugin_class'
> [#] /Users/george/.rbenv/versions/2.4.1/gemsets/crystal-news/gems/guard-2.14.1/lib/guard/plugin_util.rb:56:in `initialize_plugin'
> [#] /Users/george/.rbenv/versions/2.4.1/gemsets/crystal-news/gems/guard-2.14.1/lib/guard/internals/plugins.rb:26:in `add'
> [#] /Users/george/.rbenv/versions/2.4.1/gemsets/crystal-news/gems/guard-2.14.1/lib/guard/dsl.rb:185:in `block in guard'
> [#] /Users/george/.rbenv/versions/2.4.1/gemsets/crystal-news/gems/guard-2.14.1/lib/guard/dsl.rb:182:in `each'
> [#] /Users/george/.rbenv/versions/2.4.1/gemsets/crystal-news/gems/guard-2.14.1/lib/guard/dsl.rb:182:in `guard'```

**Comment by hawx** [comment]
I haven't touched this for many years, so probably not. I've just tried locally and it runs under Ruby 2.3.0 and Guard 2.10.2. There were a couple of other Guard plugins that did similar things so maybe try those out. Or send a PR if you find the problem and I'll be happy to merge and publish it.
